# Site settings
title: Tyler H. McIntosh
description: PhD Researcher
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tyler H. McIntosh
user_description: I'm a researcher at Queen Mary University of London, working on multitrack music performance rendering with machine Learning
user_title: PhD Researcher
email: t.h.mcintosh@qmul.ac.uk
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: tylerhmc
github_username:  TylerHMc
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

